name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.3.2
      with:
        # Name of the Azure Function App
        app-name: fsharp-functions-dotnet5
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
